### ISSUE TITLE
npm run print gives error

### ISSUE THREAD

**Issue by aryanA101a** [navn-r/resume#8]
```
(base) [aryanarora@fedora resume]$ npm run print

> resume@3.0.0 print
> node print.cjs --dev


DevTools listening on ws://127.0.0.1:42473/devtools/browser/ba25d2d3-c8e5-4fa1-b33c-53e6fd937bca
[0105/150130.970185:WARNING:vaapi_wrapper.cc(589)] VAAPI video acceleration not available for swiftshader
[0105/150130.970390:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
/home/aryanarora/projects/resume/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:155
                    ? new Error(`${response.errorText} at ${url}`)
                      ^

Error: net::ERR_CONNECTION_REFUSED at http://localhost:3000/resume/
    at navigate (/home/aryanarora/projects/resume/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:155:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FrameManager.navigateFrame (/home/aryanarora/projects/resume/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:130:21)
    at async Frame.goto (/home/aryanarora/projects/resume/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:500:16)
    at async Page.goto (/home/aryanarora/projects/resume/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async /home/aryanarora/projects/resume/print.cjs:18:3
```

**Comment by navn-r** [comment]
Hey, thanks for raising the issue. The print script has been a bit problematic ever since I switched to Svelte. Did you try running the `print` command while the dev server is running?

```
npm run dev
```

If that doesn't work, the best approach would be to follow the steps done in the [GH Action workflow](https://github.com/navn-r/resume/blob/main/.github/workflows/main.yml) locally.

PRs are also much appreciated.

**Comment by aryanA101a** [comment]
Yes, I was running print command while the dev server was running.

Github actions log:
**Print PDF**
```
Run npm run serve & sleep 5 && npm run print:ci && pkill -15 -x "npm run serve" && echo 'done'; echo $?

> resume@3.0.0 serve
> vite preview

  ➜  Local:   http://127.0.0.1:4173/resume/
  ➜  Network: use --host to expose

> resume@3.0.0 print:ci
> node print.cjs


DevTools listening on ws://127.0.0.1:34327/devtools/browser/7[6](https://github.com/aryanA101a/resume/actions/runs/3841272903/jobs/6541296995#step:7:7)662288-3a[7](https://github.com/aryanA101a/resume/actions/runs/3841272903/jobs/6541296995#step:7:8)7-4c6[8](https://github.com/aryanA101a/resume/actions/runs/3841272903/jobs/6541296995#step:7:9)-8152-7[9](https://github.com/aryanA101a/resume/actions/runs/3841272903/jobs/6541296995#step:7:10)a56c764cc8
[0[10](https://github.com/aryanA101a/resume/actions/runs/3841272903/jobs/6541296995#step:7:11)4/201353.679540:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
[0104/201353.716626:ERROR:command_buffer_proxy_impl.cc(125)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
/home/runner/work/resume/resume/node_modules/.pnpm/puppeteer@[11](https://github.com/aryanA101a/resume/actions/runs/3841272903/jobs/6541296995#step:7:12).0.0/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:155
                    ? new Error(`${response.errorText} at ${url}`)
                      ^

Error: net::ERR_CONNECTION_REFUSED at http://localhost:5000/resume/
    at navigate (/home/runner/work/resume/resume/node_modules/.pnpm/puppeteer@11.0.0/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:155:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FrameManager.navigateFrame (/home/runner/work/resume/resume/node_modules/.pnpm/puppeteer@11.0.0/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:[13](https://github.com/aryanA101a/resume/actions/runs/3841272903/jobs/6541296995#step:7:14)0:21)
    at async Frame.goto (/home/runner/work/resume/resume/node_modules/.pnpm/puppeteer@11.0.0/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:500:[16](https://github.com/aryanA101a/resume/actions/runs/3841272903/jobs/6541296995#step:7:17))
    at async Page.goto (/home/runner/work/resume/resume/node_modules/.pnpm/puppeteer@11.0.0/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async /home/runner/work/resume/resume/print.cjs:[18](https://github.com/aryanA101a/resume/actions/runs/3841272903/jobs/6541296995#step:7:19):3
1
```

**Comment by navn-r** [comment]
Fixed in https://github.com/navn-r/resume/commit/3d550bbd075781bba16deb070cd36d8056038550
